# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
    workflow_dispatch:
    repository_dispatch:
        types: [trigger_build] 

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              with:
                  repository: "kaxifakl/article-build"
                  path: "_article-build"
                  ref: "main"
                  token: ${{ secrets.PUSH_TOKEN }}
            - uses: actions/checkout@v4
              with:
                  repository: "kaxifakl/article"
                  path: "_article"
                  ref: "main"
                  token: ${{ secrets.PUSH_TOKEN }}
            - run: |
                # 将 _article 内容复制到build
                # 创建 _article-build/source/_posts 目录
                mkdir -p _article-build/source/_posts
                cp -r _article/docs/* _article-build/source/_posts
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                cd _article-build/themes/butterfly
                npm install
            - run: |
                cd _article-build
                npm install --omit=dev
                npm run build
            - name: Move public to root
              run: |
                # 清空根目录（保留 git / workflow / 构建目录）
                find . -maxdepth 1 \
                ! -name '.git' \
                ! -name '.github' \
                ! -name '_article-build' \
                ! -name '.' \
                -exec rm -rf {} +

                # 将 _article-build/public 内容平铺到根目录
                cp -r _article-build/public/* .

                # 可选：清理构建目录
                rm -rf _article-build
            - name: Commit and push
              run: |
                pwd
                # 一定要看到 .git
                ls -a   
                git config user.name "kaxifakl"
                git config user.email "1813408689@qq.com"

                git add -A
                git commit -m "build: GitHub Action"
                git push